danger:
  start-level: -64                          # couche de départ
  end-level: 250                            # couche de fin
  surface-level: 64                         # couche de surface (transition entre les 2 phases, phase cave et phase surface)
  total-time-below-surface: 6000            # duré total de la monté en cave 24000 = 20min (en tick)
  total-time-above-surface: 24000           # duré total de la monté en surface 24000 = 20min (en tick)
  damage: 1.0                               # dégâts (1 = 1 cœur)            !!!PLUS UTILISÉ!!!
  damage-every: 40                          # tous les 20 ticks = 1 seconde  !!!PLUS UTILISÉ!!!
  place-lava: true                          # active la lave
  show-alert: true                          # active l'alerte proche de la lave
  lava-margin: 30                           # marge de lave en dehors des bordures
  increase-size: 2                          # a partir de combien de nouvelle couche de lave disponible on place la lave
  lava-rising-delay: 24000                  # le delay avant que la 2eme phase se lance (en tick)
  border-size-prerise: 200                  # taille des bordures pendant la phase de préparation
  border-size-during-rise: 75               # taille des bordures pendant la phase de monter de la lave
  border-resize-time: 300                   # temps que met la bordure pour passer de sa taille pendant la phase de préparation à sa taille pendant la monter (en secondes)
  disable-pvp-during-preparation: true      # si le pvp est désactivé pendant la phase de préparation
  keepinventory-during-preparation: true    # si keepInventory est activé pendant la phase de préparation
  falldamage-reduction: 0.8                 # facteur de dégat de chute (0.8 : 0.8*falldamage)