danger:
  start-level: -64          # couche de départ
  end-level: 250           # couche de fin
  total-time: 24000        # duré total de la monté (effectif en increase-mode = 1) 24000 = 20min
  damage: 1.0              # dégâts (1 = 1 cœur)
  damage-every: 40         # tous les 20 ticks = 1 seconde
  place-lava: true         # active la lave
  show-alert: true         # active l'alerte proche de la lave
  lava-margin: 30          # marge de lave en dehors des bordures
  increase-size: 2         # a partir de combien de nouvelle couche de lave disponible on place la lave
  lava-rising-delay: 20    # le delay avant que la 2eme phase se lance